#!/usr/bin/env python3
"""Assemble the prompt for ONE gater book's daily session — input side only.

Same shape as `engine/news_analyst_prep.py`, and for the same reason: the
wrapper gathers every input and writes every output, so the model call is a pure
text -> text transform with no tools, no permission surface and no filesystem to
reason about.

Runs at ~21:40 UTC, ~50 minutes ahead of the 22:30 UTC nightly, because orders
generated by the nightly's league stage fill at the NEXT open — a veto that
arrives after `generate_orders` is a veto of a trade already made.

Everything here is READ-ONLY: a read-only DuckDB connection with a bounded
retry (the farm can hold the single writer lock), and it never writes outside
the engine repo's own scratch/prompt paths.
"""
from __future__ import annotations

import argparse
import json
import sys
import time
from datetime import date, datetime, timezone
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

AGENTS_DIR = REPO_ROOT / "agents"
NEWS_LATEST = REPO_ROOT / "data" / "reports" / "news" / "latest.md"
LEAGUE_MD = REPO_ROOT / "data" / "reports" / "league.md"
DB_PATH = REPO_ROOT / "store" / "market.duckdb"
PROMPT_FILE = AGENTS_DIR / "gater_prompt.md"

MAX_CANDIDATES = 40


def utcnow() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def read(path: Path, limit: int | None = None) -> str:
    try:
        t = path.read_text(encoding="utf-8")
    except Exception as exc:  # noqa: BLE001
        return f"(unavailable: {exc})"
    if limit and len(t) > limit:
        return t[:limit] + f"\n\n_(truncated at {limit} chars)_"
    return t


def connect_ro(db_path: Path = DB_PATH, retries: int = 6, sleep_s: float = 5.0):
    """Read-only connection with a bounded retry.

    DuckDB is single-writer and the nightly/farm can hold the lock through a
    long drain. A gater session that cannot read the store degrades to "no
    candidate preview" — it does NOT fail, and it does NOT block anything,
    because no gate file simply means the book runs pure algo.
    """
    import duckdb
    last = None
    for i in range(retries):
        try:
            return duckdb.connect(str(db_path), read_only=True)
        except Exception as exc:  # noqa: BLE001
            last = exc
            time.sleep(sleep_s * (1 if i < 3 else 2))
    raise RuntimeError(f"store locked after {retries} attempts: {last}")


def algo_preview(con, book: str) -> tuple[list[dict], str, dict]:
    """Re-run the book's OWN generate_orders read-only to see what it proposes.

    Two honesty points, both stated in the prompt:
      * at 21:40 UTC today's bars are not collected yet, so this is the LATEST
        STORED session's proposal set — an indication of what is in play, not a
        promise of tonight's orders;
      * the preview runs with `agent_gate` stripped from the params, so it shows
        the RAW algo intent rather than yesterday's gate applied to it.
    """
    from sim.portfolio import get_positions
    from sim.strategies import PortfolioView, get_strategy

    row = con.execute(
        "SELECT strategy, config, cash FROM portfolios WHERE id = ?", [book]
    ).fetchone()
    if not row:
        return [], "(book not created in the store yet)", {}
    strat_name, cfg_json, cash = row
    cfg = json.loads(cfg_json)
    params = dict(cfg.get("params", {}))
    params.pop("agent_gate", None)          # raw algo intent, ungated

    as_of = con.execute("SELECT MAX(date) FROM prices").fetchone()[0]
    eq = con.execute(
        "SELECT equity FROM sim_equity WHERE portfolio_id = ? "
        "ORDER BY date DESC LIMIT 1", [book]).fetchone()
    positions = {t: p["qty"] for t, p in get_positions(con, book).items()}
    pv = PortfolioView(id=book, params=params, cash=float(cash or 0.0),
                       positions=positions,
                       equity=float(eq[0]) if eq else float(cash or 0.0))
    orders = get_strategy(strat_name).generate_orders(con, pv, as_of)

    cands = []
    for o in orders:
        if o.side != "buy":
            continue
        px = con.execute(
            "SELECT close FROM prices WHERE ticker = ? AND date <= ? "
            "ORDER BY date DESC LIMIT 1", [o.ticker, as_of]).fetchone()
        px = float(px[0]) if px and px[0] is not None else None
        cands.append({"ticker": o.ticker, "qty": round(o.qty, 4),
                      "close": px,
                      "notional": round(o.qty * px, 2) if px else None})
    cands.sort(key=lambda c: -(c["notional"] or 0))
    return cands[:MAX_CANDIDATES], str(as_of), positions


def recent_earnings(con, as_of: str, n_sessions: int = 2) -> str:
    """Names whose earnings landed in the last `n_sessions` — point-in-time.

    `as_of <=` mirrors the discipline `pead_ear` itself uses, so a session can
    never see an earnings date that was only restated later.
    """
    try:
        sessions = [r[0] for r in con.execute(
            "SELECT DISTINCT date FROM prices WHERE date <= ? "
            "ORDER BY date DESC LIMIT ?", [as_of, n_sessions]).fetchall()]
        if not sessions:
            return "(no sessions)"
        rows = con.execute(
            "SELECT DISTINCT ticker FROM earnings_calendar "
            "WHERE as_of <= ? AND earnings_date >= ? AND earnings_date <= ? "
            "ORDER BY ticker", [as_of, min(sessions), max(sessions)]).fetchall()
    except Exception as exc:  # noqa: BLE001 — table may be absent on a copy
        return f"(unavailable: {exc})"
    if not rows:
        return "(no names with earnings in the window)"
    return ", ".join(r[0] for r in rows[:200])


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--book", required=True)
    ap.add_argument("--prompt-out", required=True)
    ap.add_argument("--meta-out", required=True)
    ap.add_argument("--date", default=date.today().isoformat())
    ap.add_argument("--agents-dir", default=str(AGENTS_DIR))
    # --db exists so the whole loop can be shaken down against a COPY of the
    # store; production always uses the default.
    ap.add_argument("--db", default=str(DB_PATH))
    a = ap.parse_args()

    agents_dir = Path(a.agents_dir)
    meta = {"book": a.book, "date": a.date, "generated_utc": utcnow(),
            "n_candidates": 0, "db_ok": True, "book_exists": True}

    cands: list[dict] = []
    bars_as_of = "(unknown)"
    positions: dict = {}
    earnings = "(not queried)"
    try:
        con = connect_ro(Path(a.db))
        try:
            cands, bars_as_of, positions = algo_preview(con, a.book)
            meta["book_exists"] = bars_as_of != "(book not created in the store yet)"
            if a.book == "earnings_context_pead" and meta["book_exists"]:
                earnings = recent_earnings(con, bars_as_of)
            league = read(LEAGUE_MD, 6000)
        finally:
            con.close()
    except Exception as exc:  # noqa: BLE001
        meta["db_ok"] = False
        meta["db_error"] = str(exc)
        league = "(unavailable: store locked)"

    meta["n_candidates"] = len(cands)
    meta["bars_as_of"] = bars_as_of

    cand_lines = "\n".join(
        f"- **{c['ticker']}** — algo would buy {c['qty']} sh "
        f"@ last close {c['close']} (≈${c['notional']:,.0f})"
        if c["close"] else f"- **{c['ticker']}** — algo would buy {c['qty']} sh "
                           f"(no close available)"
        for c in cands) or "_(the algo proposed no new entries on the latest " \
                           "stored session)_"

    parts = [
        read(PROMPT_FILE),
        "", "---", "",
        f"## INPUT A — This book's FROZEN CHARTER (`{a.book}`)", "",
        read(agents_dir / a.book / "charter.md"),
        "", "---", "",
        "## INPUT B — Lessons so far (append-only memory)", "",
        read(agents_dir / a.book / "lessons.md", 20000),
        "", "---", "",
        "## INPUT C — Today's news brief", "",
        read(NEWS_LATEST, 30000),
        "", "---", "",
        f"## INPUT D — Algo candidate PREVIEW ({len(cands)} name(s))",
        "",
        f"_Generated by re-running this book's own `generate_orders` read-only "
        f"against the latest stored session (**{bars_as_of}**), with the gate "
        f"stripped so this is the RAW algo intent. Today's bars are not "
        f"collected yet at this hour, so treat this as **what is in play**, not "
        f"as tonight's guaranteed order list. A decision on a name that does "
        f"not end up proposed is simply inert._",
        "", cand_lines,
    ]
    if a.book == "earnings_context_pead":
        parts += ["", "---", "",
                  "## INPUT E — Names with earnings in the last 2 sessions "
                  "(point-in-time)", "", earnings]
    parts += [
        "", "---", "",
        "## INPUT F — This book's current holdings", "",
        (", ".join(f"{t} ({q:.2f} sh)" for t, q in sorted(positions.items()))
         or "_(no open positions)_"),
        "", "---", "",
        "## INPUT G — Paper league standings", "", league,
        "", "---", "",
        f"Today is {a.date}. Produce the gate decision for `{a.book}` now, as a "
        f"single JSON object and nothing else, following the output contract at "
        f"the top.",
        "",
    ]

    Path(a.prompt_out).write_text("\n".join(parts), encoding="utf-8")
    Path(a.meta_out).write_text(json.dumps(meta, indent=2) + "\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
