#!/usr/bin/env bash
# Daily entry-gate sessions for the two gater books (agentic-strategies-design
# books 1 and 5). Reuses the PROVEN news-analyst harness shape exactly:
# zero-tool `claude -p` on the subscription login, wrapper does all I/O.
#
# TIMING IS THE WHOLE POINT. Orders are generated by the 22:30 UTC nightly's
# league stage and fill at the NEXT open, so a veto must exist BEFORE
# generate_orders runs. Cron: 40 21 * * 1-5 — ~50 minutes of headroom.
#
# FAIL-SOFT, ALWAYS. Every path logs a breadcrumb and exits 0. A dead session,
# an exhausted quota, a locked store, a malformed response — all of them mean
# "no gate file", and no gate file means the book runs on pure algo. The agent
# is an overlay; it must never be a prerequisite for the nightly.

set -uo pipefail

# cron gives a near-empty environment; the Claude CLI needs HOME to find its
# subscription OAuth credentials (~/.claude/.credentials.json).
export HOME="${HOME:-/data00/home/jun.ong}"
export PATH="${HOME}/.local/bin:/usr/local/bin:/usr/bin:/bin"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
cd "${REPO_ROOT}" || exit 0

PY="${REPO_ROOT}/.venv/bin/python"
CLAUDE="${HOME}/.local/bin/claude"
LOG="${REPO_ROOT}/logs/agentic-gater.log"
RUN_DATE="${GATER_DATE:-$(date -u +%F)}"
AGENTS_DIR="${TRADING_ENGINE_AGENTS_DIR:-${REPO_ROOT}/agents}"
BOOKS="${GATER_BOOKS:-news_gated_momo earnings_context_pead}"
# Shakedown seam only: production leaves GATER_DB unset and the default store is used.
DB_ARG="${GATER_DB:-}"

mkdir -p "${REPO_ROOT}/logs" "${REPO_ROOT}/scratch"
log() { echo "$(date -u +%FT%TZ) $*" >> "${LOG}"; }

exec 9>"${REPO_ROOT}/.agentic-gater.lock"
if ! flock -n 9; then
  log "SKIP: another gater run holds the lock"
  exit 0
fi

log "=== gater run start (${RUN_DATE}) books='${BOOKS}' ==="

WORK="$(mktemp -d "${REPO_ROOT}/scratch/gater.XXXXXX")" || {
  log "TODO: could not create work dir — skipping this run"; exit 0; }
# shellcheck disable=SC2064
trap "rm -rf '${WORK}'" EXIT

# jq is not installed on this box; the venv python is always present. Kept as a
# preference order in case jq ever shows up.
jread() {  # jread <file> <jq-filter> <python-expression over `d`>
  if command -v jq >/dev/null 2>&1; then jq -r "$2" < "$1"
  else "${PY}" -c "import json,sys; d=json.load(open(sys.argv[1])); sys.stdout.write(str($3))" "$1"; fi
}

# Tools are removed outright rather than merely unused: verified 2026-08-04 that
# the model reports no Bash tool available under this deny-list. `--bare` is NOT
# used — it reads ANTHROPIC_API_KEY/apiKeyHelper only and never OAuth, so on this
# box's subscription login every --bare call returns "Not logged in".
NO_TOOLS='{"permissions":{"deny":["Bash","Edit","Write","Read","Agent","WebFetch","WebSearch","Skill","NotebookEdit","Glob","Grep","Task","TodoWrite"]}}'

for BOOK in ${BOOKS}; do
  log "--- ${BOOK} ---"
  PROMPT="${WORK}/${BOOK}.prompt.txt"
  META="${WORK}/${BOOK}.meta.json"
  OUT_JSON="${WORK}/${BOOK}.out.json"

  if ! "${PY}" "${SCRIPT_DIR}/gater_prep.py" --book "${BOOK}" \
        --prompt-out "${PROMPT}" --meta-out "${META}" --date "${RUN_DATE}" \
        --agents-dir "${AGENTS_DIR}" ${DB_ARG:+--db "${DB_ARG}"} >>"${LOG}" 2>&1; then
    log "TODO: ${BOOK} prep failed — no gate file, book runs pure algo"
    continue
  fi

  N_CAND="$(jread "${META}" '.n_candidates' 'd["n_candidates"]')"
  case "${N_CAND}" in ''|*[!0-9]*) N_CAND=0 ;; esac
  BOOK_EXISTS="$(jread "${META}" '.book_exists' 'd["book_exists"]')"
  if [ "${BOOK_EXISTS}" != "True" ] && [ "${BOOK_EXISTS}" != "true" ]; then
    log "OK: ${BOOK} is not in the store yet (league --init has not created it)" \
        "— no gate file, nothing to gate"
    continue
  fi
  log "INFO: ${BOOK} candidates=${N_CAND} prompt=$(wc -c < "${PROMPT}") bytes"

  # A zero-candidate day still runs the session for book 5 ONLY if there are
  # earnings names to classify; for book 1 an empty candidate list means there
  # is nothing a veto could possibly bind on, so skip the call and the quota.
  if [ "${N_CAND}" -eq 0 ] && [ "${BOOK}" = "news_gated_momo" ]; then
    log "OK: ${BOOK} — algo proposed 0 entries; no claude call, no gate file"
    continue
  fi

  if ! timeout 600 "${CLAUDE}" -p "$(cat "${PROMPT}")" \
        --permission-mode dontAsk \
        --strict-mcp-config \
        --settings "${NO_TOOLS}" \
        --max-turns 1 \
        --output-format json > "${OUT_JSON}" 2>>"${LOG}"; then
    log "TODO: ${BOOK} claude -p exited non-zero (quota / auth / network?) —" \
        "no gate file, book runs pure algo. Inspect ${LOG}."
    continue
  fi

  IS_ERROR="$(jread "${OUT_JSON}" '.is_error' 'd.get("is_error", False)' 2>>"${LOG}")"
  if [ "${IS_ERROR}" = "true" ] || [ "${IS_ERROR}" = "True" ]; then
    log "TODO: ${BOOK} claude reported is_error=true" \
        "($(jread "${OUT_JSON}" '.result' 'str(d.get("result",""))[:200]')) — no gate file"
    continue
  fi

  # The model is asked for bare JSON, but a stray fence or a sentence of preamble
  # must not cost the day's gate — extract the outermost JSON object.
  PROPOSAL="${WORK}/${BOOK}.proposal.json"
  if ! "${PY}" - "${OUT_JSON}" "${PROPOSAL}" <<'PYEOF' >>"${LOG}" 2>&1; then
import json, re, sys
raw = json.load(open(sys.argv[1])).get("result", "") or ""
m = re.search(r"\{.*\}", raw, re.S)
if not m:
    print(f"[gater] no JSON object in the model response (first 200 chars): {raw[:200]!r}")
    raise SystemExit(1)
obj = json.loads(m.group(0))
json.dump(obj, open(sys.argv[2], "w"), indent=2)
PYEOF
    log "TODO: ${BOOK} could not parse a JSON proposal out of the response — no gate file"
    continue
  fi

  # The validator is the only thing that may write a gate file. It enforces the
  # charter's bounds, drops row-level violations, rejects file-level ones, and
  # appends to changes.jsonl for applied AND rejected proposals alike.
  "${PY}" "${SCRIPT_DIR}/validator.py" --book "${BOOK}" \
      --proposal "${PROPOSAL}" --date "${RUN_DATE}" \
      --agents-dir "${AGENTS_DIR}" --n-candidates "${N_CAND}" \
      --session "gater-${RUN_DATE}" ${DB_ARG:+--db "${DB_ARG}"} >>"${LOG}" 2>&1 \
    || log "WARN: ${BOOK} validator exited non-zero — treat as no gate file"
done

log "=== gater run done (${RUN_DATE}) ==="
exit 0
